### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ProjectVexion** [TrinityyTeam/issues#30]
Just want to see how quick i get blocked lol, hello

**Comment by ProjectVexion** [comment]
can't add my own labels lol

**Comment by SliceCraft** [comment]
> Just want to see how quick i get blocked lol, hello
Well please don't

> can't add my own labels lol
Looking into that now

**Comment by SliceCraft** [comment]
Apparently that isn't possible for non contributors so guess I'll need to add labels manually.
