### ISSUE TITLE
Auto levelrewards check

### ISSUE THREAD

**Issue by SliceCraft** [TrinityyTeam/issues#37]
When you send a message automatically check if a user has the levelrewards they are supposed to have. If they don't have the levelrewards they will receive the missing levelrewards.

**Comment by SliceCraft** [comment]
The user will now receive all missing levelrewards at the next moment a user receives xp.

**Comment by CasparN** [comment]
I must thank you for this addition, this is pretty handy for multiple occasions and I think this was a great addition for the Trinity discord bot.
