### ISSUE TITLE
Redo some commands

### ISSUE THREAD

**Issue by CasparN** [TrinityyTeam/issues#50]
So
/ticket new 
To make ticket
/ticket close
To close ticket
/suggestion approve
to approve instead of /approve
/suggestion deny
instead of /deny
this will improve the big chungus.

**Comment by SliceCraft** [comment]
I added it to Release 1.5 but it's possible that I decide to do this in Release 1.4.1 or 1.4.2

**Comment by CasparN** [comment]
gud.

**Comment by SliceCraft** [comment]
Sorry for the weird switching between milestones above.
All ticket commands can now be used as sub commands from the `ticket` command.
