### ISSUE TITLE
Automatically delete you dont have perms

### ISSUE THREAD

**Issue by CasparN** [TrinityyTeam/issues#52]
Automatically self destruction of: You don't have the appropriate permissions to do this specific command 
Well that isn't the exact name but u get what I mean
Also with the please specify a user n stuff in general just with error messages delete them after a minute or so is my suggestion  :)

**Comment by CasparN** [comment]
you have a point there. fuck. but now I cant threaten people anymore when I want to just do /ban to threaten them sadly.
my suggestion was with the non-slash commands cuz they cluttered up the chat a little bit. I do hope you will get that message intent so I can threaten people again using ;ban

**Comment by SliceCraft** [comment]
Non slash commands (aka legacy commands) will be removed (and replaced with a temporary note) in the next update. So this change isn't possible.

**Comment by CasparN** [comment]
understandable have a nice day
